# Generated by Django 5.2.8 on 2025-11-14 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchstore', '0002_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='password_hash',
        ),
    ]
